### ISSUE TITLE
Request: Release _pretrained_models/imagenet.ckpt

### ISSUE THREAD

**Issue by DoubleS-S** [deabfc/dp-promise#1]
Hey there! 👋

First, awesome work on this project! 🎉

I was wondering if you could release the `_pretrained_models/imagenet.ckpt` file? It would be super helpful for those of us working with your project.

Thanks for considering this request, and keep up the great work! 😊

**Comment by deabfc** [comment]
Thank you for reaching out.

The file `_pretrained_models/imagenet.ckpt` is a checkpoint of the diffusion model pre-trained on ImageNet 32x32. The corresponding configuration for this pre-trained model can be found in `configs/vanilla/imagenet_32/config.yaml`.

To obtain this checkpoint, please run the `pretrain.py` script.

**Comment by hmsklv0** [comment]
> Thank you for reaching out.
> 
> The file `_pretrained_models/imagenet.ckpt` is a checkpoint of the diffusion model pre-trained on ImageNet 32x32. The corresponding configuration for this pre-trained model can be found in `configs/vanilla/imagenet_32/config.yaml`.
> 
> To obtain this checkpoint, please run the `pretrain.py` script.

Hello, I couldn't find the code that saves the trained model to the _pretrained_models directory in the project files. Could you please provide the specific code for saving the model?
